# properties
projectName=operaton-cockpit

# versions
kotlinVersion=2.1.20
kotlinLoggingVersion=7.0.7
springBootVersion=3.5.7
springDependencyManagementVersion=1.1.7
operatonVersion=1.0.0-beta-4
postgresqlDriverVersion=42.7.5
ideaExt=1.1.10
dotenvVersion=4.0.0
jsonschema2pojoVersion=1.1.1

org.gradle.jvmargs=-Xms128m -Xmx2048m -Duser.timezone=UTC

# Use .env.properties instead of the default .env for backwards compatibility
dotenv.filename=.env.properties
